import type { ArchitectureContext, BusinessState } from './businessDiscovery'
import type { ModuleId } from './blueprint'
import { researchBusiness, type BusinessResearch } from './businessResearch'
import { capability, currency, date, entity, long, number, relation, select, text } from '../data/capabilityHelpers'
import { extendedIndustryPacks } from '../data/industryPacks'
import { commerceCapabilities } from '../data/capabilities.commerce'
import { operationsCapabilities } from '../data/capabilities.operations'
import { financeCapabilities } from '../data/capabilities.finance'
import { saysSignal } from './shared'

export type CatalogFieldType = 'text' | 'long-text' | 'number' | 'currency' | 'date' | 'boolean' | 'email' | 'phone' | 'select' | 'relation' | 'file'

export interface CatalogField {
  id: string
  label: string
  type: CatalogFieldType
  required?: boolean
  options?: string[]
  relationEntityId?: string
}

export interface CatalogEntity {
  id: string
  label: string
  pluralLabel: string
  primaryField: string
  fields: CatalogField[]
  view?: 'table' | 'kanban' | 'calendar'
  groupBy?: string
  dateField?: string
}

export interface CatalogMetric {
  id: string
  label: string
  entityId: string
  operation: 'count' | 'sum'
  field?: string
  format?: 'number' | 'currency'
  statusNotEquals?: string
}

export interface CatalogWorkflow {
  id: string
  name: string
  entityId: string
  event: 'created' | 'updated'
  field?: string
  equals?: string
  message: string
}

export interface CapabilityDefinition {
  id: string
  label: string
  module: ModuleId
  description: string
  signals: string[]
  dependencies: string[]
  entities: CatalogEntity[]
  pages: Array<{ id: string; label: string; entityId: string; view?: 'table' | 'kanban' | 'calendar' }>
  metrics?: CatalogMetric[]
  workflows?: CatalogWorkflow[]
}


const coreCapabilities: CapabilityDefinition[] = [
  capability({ id: 'crm.contacts', label: 'Contacts and accounts', module: 'customers', description: 'People and organizations with complete relationship history.', signals: ['customer', 'client', 'contact', 'patient', 'member', 'tenant'], dependencies: [], entities: [entity('customers', 'Client', 'Clients', 'name', [text('name', 'Name', true), select('status', 'Status', ['Lead', 'Active', 'Inactive']), { id: 'email', label: 'Email', type: 'email' }, { id: 'phone', label: 'Phone', type: 'phone' }, text('address', 'Address'), long('notes', 'Notes')])], pages: [{ id: 'customers', label: 'Clients', entityId: 'customers' }], metrics: [{ id: 'active-customers', label: 'Active accounts', entityId: 'customers', operation: 'count' }] }),
  capability({ id: 'crm.pipeline', label: 'Lead and deal pipeline', module: 'sales', description: 'Prospects, opportunities, stages, owners and expected value.', signals: ['lead', 'pipeline', 'prospect', 'opportunity', 'deal', 'sales team'], dependencies: ['crm.contacts'], entities: [entity('opportunities', 'Opportunity', 'Pipeline', 'name', [text('name', 'Opportunity', true), relation('customer', 'Client', 'customers'), select('status', 'Stage', ['New', 'Qualified', 'Proposal', 'Negotiation', 'Won', 'Lost']), currency('amount', 'Expected value'), date('dueDate', 'Expected close'), long('notes', 'Notes')], 'kanban', 'status')], pages: [{ id: 'sales', label: 'Pipeline', entityId: 'opportunities', view: 'kanban' }], metrics: [{ id: 'pipeline-value', label: 'Pipeline value', entityId: 'opportunities', operation: 'sum', field: 'amount', format: 'currency', statusNotEquals: 'Lost' }] }),
  capability({ id: 'crm.activities', label: 'Sales activities', module: 'sales', description: 'Calls, meetings and next actions linked to prospects and accounts.', signals: ['follow up', 'sales activity', 'call', 'meeting'], dependencies: ['crm.contacts'], entities: [entity('activities', 'Activity', 'Activities', 'subject', [text('subject', 'Activity', true), relation('customer', 'Client', 'customers'), select('type', 'Type', ['Call', 'Email', 'Meeting', 'Task']), date('dueDate', 'Due date'), select('status', 'Status', ['Planned', 'Complete'])], 'calendar', undefined, 'dueDate')], pages: [{ id: 'sales-activities', label: 'Sales activities', entityId: 'activities', view: 'calendar' }] }),
  capability({ id: 'sales.quotes', label: 'Estimates and quotes', module: 'sales', description: 'Commercial estimates before an order or contract.', signals: ['quote', 'estimate', 'proposal', 'rfq', 'bid'], dependencies: ['crm.contacts'], entities: [entity('quotes', 'Quote', 'Quotes', 'number', [text('number', 'Quote number', true), relation('customer', 'Client', 'customers'), select('status', 'Status', ['Draft', 'Sent', 'Accepted', 'Rejected', 'Expired']), currency('amount', 'Total'), date('validUntil', 'Valid until'), long('scope', 'Scope')])], pages: [{ id: 'quotes', label: 'Quotes', entityId: 'quotes' }], metrics: [{ id: 'open-quotes', label: 'Open quotes', entityId: 'quotes', operation: 'count', statusNotEquals: 'Accepted' }] }),
  capability({ id: 'sales.contracts', label: 'Contracts and agreements', module: 'sales', description: 'Signed terms, dates, values and renewal obligations.', signals: ['contract', 'agreement', 'retainer', 'engagement'], dependencies: ['crm.contacts'], entities: [entity('contracts', 'Contract', 'Contracts', 'name', [text('name', 'Contract', true), relation('customer', 'Client', 'customers'), select('status', 'Status', ['Draft', 'Awaiting signature', 'Active', 'Expired', 'Terminated']), date('startDate', 'Start date'), date('endDate', 'End date'), currency('amount', 'Contract value'), { id: 'file', label: 'Contract file', type: 'file' }])], pages: [{ id: 'contracts', label: 'Contracts', entityId: 'contracts' }], workflows: [{ id: 'contract-expiry', name: 'Contract expiry reminder', entityId: 'contracts', event: 'updated', field: 'status', equals: 'Expired', message: 'A contract has expired.' }] }),
  capability({ id: 'sales.orders', label: 'Sales orders', module: 'sales', description: 'Confirmed customer orders and fulfilment status.', signals: ['sales order', 'customer order', 'order management'], dependencies: ['crm.contacts'], entities: [entity('orders', 'Order', 'Orders', 'number', [text('number', 'Order number', true), relation('customer', 'Client', 'customers'), select('status', 'Status', ['Draft', 'Confirmed', 'In progress', 'Fulfilled', 'Cancelled']), currency('amount', 'Total'), date('dueDate', 'Required date')], 'kanban', 'status')], pages: [{ id: 'orders', label: 'Orders', entityId: 'orders', view: 'kanban' }], metrics: [{ id: 'open-orders', label: 'Open orders', entityId: 'orders', operation: 'count', statusNotEquals: 'Fulfilled' }] }),
  capability({ id: 'crm.client-portal', label: 'Client portal', module: 'customers', description: 'External access for progress, files, approvals and requests.', signals: ['client portal', 'customer portal', 'private portal', 'upload files'], dependencies: ['crm.contacts', 'documents.repository'], entities: [entity('portal-requests', 'Portal request', 'Portal requests', 'subject', [text('subject', 'Request', true), relation('customer', 'Client', 'customers'), select('status', 'Status', ['New', 'In progress', 'Waiting for client', 'Resolved']), long('message', 'Message')], 'kanban', 'status')], pages: [{ id: 'client-portal', label: 'Client portal', entityId: 'portal-requests', view: 'kanban' }] }),

  capability({ id: 'marketing.campaigns', label: 'Marketing campaigns', module: 'marketing', description: 'Campaign plans, channels, budget and results.', signals: ['marketing campaign', 'advertising', 'campaign performance', 'lead source'], dependencies: [], entities: [entity('campaigns', 'Campaign', 'Campaigns', 'name', [text('name', 'Campaign', true), select('status', 'Status', ['Draft', 'Active', 'Paused', 'Complete']), text('channel', 'Channel'), currency('budget', 'Budget'), date('startDate', 'Start date'), date('endDate', 'End date')], 'kanban', 'status')], pages: [{ id: 'marketing', label: 'Campaigns', entityId: 'campaigns', view: 'kanban' }] }),
  capability({ id: 'marketing.email', label: 'Email marketing', module: 'marketing', description: 'Audience lists, campaigns and delivery results.', signals: ['newsletter', 'email marketing', 'mailing list'], dependencies: ['crm.contacts'], entities: [entity('mailings', 'Mailing', 'Email campaigns', 'subject', [text('subject', 'Subject', true), select('status', 'Status', ['Draft', 'Scheduled', 'Sent']), date('scheduledAt', 'Send date'), number('recipients', 'Recipients'), number('opens', 'Opens')])], pages: [{ id: 'email-marketing', label: 'Email marketing', entityId: 'mailings' }] }),
  capability({ id: 'marketing.attribution', label: 'Lead-source attribution', module: 'marketing', description: 'Sources, campaigns and conversion outcomes.', signals: ['attribution', 'where leads come from', 'lead source', 'conversion source'], dependencies: ['crm.pipeline'], entities: [entity('lead-sources', 'Lead source', 'Lead sources', 'name', [text('name', 'Source', true), currency('spend', 'Spend'), number('leads', 'Leads'), number('customers', 'Customers')])], pages: [{ id: 'lead-sources', label: 'Lead sources', entityId: 'lead-sources' }] }),

  capability({ id: 'commerce.products', label: 'Product and service catalog', module: 'commerce', description: 'Sellable offers, pricing, variants and availability.', signals: ['product', 'service catalog', 'sku', 'price list', 'offer'], dependencies: [], entities: [entity('products', 'Product', 'Products', 'name', [text('name', 'Product', true), text('sku', 'SKU'), select('type', 'Type', ['Physical', 'Digital', 'Service']), currency('price', 'Price'), select('status', 'Status', ['Active', 'Archived']), long('description', 'Description')])], pages: [{ id: 'products', label: 'Products', entityId: 'products' }] }),
  capability({ id: 'commerce.ecommerce', label: 'E-commerce orders', module: 'commerce', description: 'Online checkout, orders and fulfilment.', signals: ['ecommerce', 'online store', 'web shop', 'checkout'], dependencies: ['commerce.products', 'sales.orders', 'finance.payments'], entities: [entity('store-orders', 'Store order', 'Store orders', 'number', [text('number', 'Order number', true), relation('customer', 'Client', 'customers'), select('status', 'Status', ['Placed', 'Paid', 'Picking', 'Shipped', 'Delivered', 'Returned']), currency('amount', 'Total'), date('createdDate', 'Order date')], 'kanban', 'status')], pages: [{ id: 'online-orders', label: 'Online orders', entityId: 'store-orders', view: 'kanban' }] }),
  capability({ id: 'commerce.pos', label: 'Point of sale', module: 'commerce', description: 'In-person transactions, shifts and till totals.', signals: ['point of sale', 'cash register', 'till', 'checkout counter', 'retail store', 'restaurant'], dependencies: ['commerce.products', 'finance.payments'], entities: [entity('pos-sessions', 'POS session', 'Point of sale', 'number', [text('number', 'Session', true), select('status', 'Status', ['Open', 'Closed']), currency('sales', 'Sales'), currency('cashVariance', 'Cash variance'), date('date', 'Date')])], pages: [{ id: 'point-of-sale', label: 'Point of sale', entityId: 'pos-sessions' }] }),
  capability({ id: 'commerce.returns', label: 'Returns and refunds', module: 'commerce', description: 'Return requests, received items and refunds.', signals: ['return', 'refund', 'money back', 'warranty claim'], dependencies: ['sales.orders'], entities: [entity('returns', 'Return', 'Returns', 'number', [text('number', 'Return number', true), relation('order', 'Order', 'orders'), select('status', 'Status', ['Requested', 'Approved', 'Received', 'Refunded', 'Rejected']), currency('amount', 'Refund amount'), long('reason', 'Reason')], 'kanban', 'status')], pages: [{ id: 'returns', label: 'Returns', entityId: 'returns', view: 'kanban' }] }),
  capability({ id: 'subscriptions.billing', label: 'Subscriptions and recurring billing', module: 'subscriptions', description: 'Plans, recurring charges, renewals and churn.', signals: ['subscription', 'recurring payment', 'monthly retainer', 'membership', 'renewal'], dependencies: ['crm.contacts', 'finance.invoicing'], entities: [entity('subscriptions', 'Subscription', 'Subscriptions', 'name', [text('name', 'Subscription', true), relation('customer', 'Client', 'customers'), select('status', 'Status', ['Trial', 'Active', 'Past due', 'Paused', 'Cancelled']), currency('amount', 'Recurring amount'), select('cadence', 'Cadence', ['Monthly', 'Quarterly', 'Yearly']), date('renewalDate', 'Renewal date')])], pages: [{ id: 'subscriptions', label: 'Subscriptions', entityId: 'subscriptions' }], metrics: [{ id: 'recurring-revenue', label: 'Recurring revenue', entityId: 'subscriptions', operation: 'sum', field: 'amount', format: 'currency', statusNotEquals: 'Cancelled' }] }),
  capability({ id: 'subscriptions.success', label: 'Customer success and renewals', module: 'subscriptions', description: 'Onboarding, adoption, health and renewal work.', signals: ['customer success', 'onboarding', 'adoption', 'renewal', 'churn'], dependencies: ['subscriptions.billing'], entities: [entity('success-plans', 'Success plan', 'Customer success', 'name', [text('name', 'Account', true), relation('customer', 'Client', 'customers'), select('health', 'Health', ['Healthy', 'At risk', 'Critical']), date('renewalDate', 'Renewal date'), long('nextStep', 'Next step')])], pages: [{ id: 'customer-success', label: 'Customer success', entityId: 'success-plans' }], metrics: [{ id: 'at-risk-accounts', label: 'At-risk accounts', entityId: 'success-plans', operation: 'count' }] }),

  capability({ id: 'work.projects', label: 'Projects and engagements', module: 'projects', description: 'Delivery scope, owners, dates, budgets and status.', signals: ['project', 'engagement', 'campaign delivery', 'client work'], dependencies: ['crm.contacts'], entities: [entity('projects', 'Project', 'Projects', 'name', [text('name', 'Project', true), relation('customer', 'Client', 'customers'), select('status', 'Status', ['Planned', 'Active', 'On hold', 'Complete']), date('startDate', 'Start date'), date('dueDate', 'Due date'), currency('budget', 'Budget')], 'kanban', 'status')], pages: [{ id: 'projects', label: 'Projects', entityId: 'projects', view: 'kanban' }], metrics: [{ id: 'active-projects', label: 'Active projects', entityId: 'projects', operation: 'count', statusNotEquals: 'Complete' }] }),
  capability({ id: 'work.tasks', label: 'Tasks and dependencies', module: 'projects', description: 'Assigned work, priorities, due dates and dependencies.', signals: ['task', 'to do', 'assignment', 'dependency', 'checklist'], dependencies: ['work.projects', 'people.directory'], entities: [entity('tasks', 'Task', 'Tasks', 'title', [text('title', 'Task', true), relation('project', 'Project', 'projects'), select('status', 'Status', ['To do', 'In progress', 'Blocked', 'Done']), select('priority', 'Priority', ['Low', 'Normal', 'High', 'Urgent']), relation('assignee', 'Assigned to', 'employees'), date('dueDate', 'Due date')], 'kanban', 'status')], pages: [{ id: 'tasks', label: 'Tasks', entityId: 'tasks', view: 'kanban' }] }),
  capability({ id: 'work.time', label: 'Time tracking', module: 'projects', description: 'Billable and non-billable time by person, project and task.', signals: ['time tracking', 'timesheet', 'billable hours', 'hourly'], dependencies: ['work.projects', 'people.directory'], entities: [entity('time-entries', 'Time entry', 'Timesheets', 'description', [text('description', 'Work', true), relation('project', 'Project', 'projects'), relation('employee', 'Team member', 'employees'), number('hours', 'Hours'), select('billable', 'Billable', ['Yes', 'No']), date('date', 'Date')])], pages: [{ id: 'timesheets', label: 'Timesheets', entityId: 'time-entries' }], metrics: [{ id: 'billable-hours', label: 'Tracked hours', entityId: 'time-entries', operation: 'sum', field: 'hours' }] }),
  capability({ id: 'work.resources', label: 'Resource and capacity planning', module: 'projects', description: 'Workload, availability and allocation across the team.', signals: ['capacity', 'resource allocation', 'workload', 'availability', 'who is working'], dependencies: ['people.directory', 'work.projects'], entities: [entity('allocations', 'Allocation', 'Resource planning', 'name', [text('name', 'Allocation', true), relation('employee', 'Team member', 'employees'), relation('project', 'Project', 'projects'), number('hours', 'Allocated hours'), date('startDate', 'Start date'), date('endDate', 'End date')], 'calendar', undefined, 'startDate')], pages: [{ id: 'resources', label: 'Resource planning', entityId: 'allocations', view: 'calendar' }] }),
  capability({ id: 'work.scheduling', label: 'Appointments and scheduling', module: 'scheduling', description: 'Bookable appointments, shifts or service dates.', signals: ['appointment', 'calendar', 'schedule', 'booking', 'reservation'], dependencies: ['crm.contacts', 'people.directory'], entities: [entity('appointments', 'Appointment', 'Schedule', 'title', [text('title', 'Appointment', true), relation('customer', 'Client', 'customers'), date('scheduledDate', 'Date'), text('time', 'Time'), select('status', 'Status', ['Scheduled', 'Confirmed', 'In progress', 'Complete', 'Cancelled']), relation('assignee', 'Assigned to', 'employees')], 'calendar', undefined, 'scheduledDate')], pages: [{ id: 'schedule', label: 'Schedule', entityId: 'appointments', view: 'calendar' }] }),
  capability({ id: 'service.field-work', label: 'Field service and dispatch', module: 'field-service', description: 'Requests, work orders, technicians, visits and completion.', signals: ['field service', 'dispatch', 'technician', 'installation', 'repair', 'service visit'], dependencies: ['crm.contacts', 'work.scheduling', 'people.directory'], entities: [entity('work-orders', 'Work order', 'Work orders', 'number', [text('number', 'Work order', true), relation('customer', 'Client', 'customers'), select('status', 'Status', ['New', 'Scheduled', 'Dispatched', 'In progress', 'Complete', 'Cancelled']), relation('assignee', 'Technician', 'employees'), date('scheduledDate', 'Scheduled date'), text('address', 'Service address'), long('workPerformed', 'Work performed')], 'kanban', 'status')], pages: [{ id: 'field-service', label: 'Work orders', entityId: 'work-orders', view: 'kanban' }], metrics: [{ id: 'open-work-orders', label: 'Open work orders', entityId: 'work-orders', operation: 'count', statusNotEquals: 'Complete' }] }),
  capability({ id: 'service.assets', label: 'Customer assets and equipment', module: 'field-service', description: 'Installed assets, serial numbers, warranty and service history.', signals: ['customer asset', 'installed equipment', 'serial number', 'warranty', 'machine service'], dependencies: ['crm.contacts'], entities: [entity('service-assets', 'Asset', 'Customer assets', 'name', [text('name', 'Asset', true), relation('customer', 'Client', 'customers'), text('serialNumber', 'Serial number'), text('model', 'Model'), date('warrantyUntil', 'Warranty until'), select('status', 'Status', ['Active', 'Out of service', 'Retired'])])], pages: [{ id: 'customer-assets', label: 'Customer assets', entityId: 'service-assets' }] }),

  capability({ id: 'procurement.suppliers', label: 'Suppliers and vendors', module: 'procurement', description: 'Vendor records, terms, contacts and performance.', signals: ['supplier', 'vendor', 'manufacturer', 'outside supplier'], dependencies: [], entities: [entity('suppliers', 'Supplier', 'Suppliers', 'name', [text('name', 'Supplier', true), select('status', 'Status', ['Active', 'On hold', 'Inactive']), { id: 'email', label: 'Email', type: 'email' }, { id: 'phone', label: 'Phone', type: 'phone' }, text('paymentTerms', 'Payment terms'), long('notes', 'Notes')])], pages: [{ id: 'suppliers', label: 'Suppliers', entityId: 'suppliers' }] }),
  capability({ id: 'procurement.purchasing', label: 'Purchase orders', module: 'procurement', description: 'Requests, approvals, purchase orders and receipts.', signals: ['purchase order', 'procurement', 'buy materials', 'purchasing', 'requisition'], dependencies: ['procurement.suppliers'], entities: [entity('purchase-orders', 'Purchase order', 'Purchase orders', 'number', [text('number', 'PO number', true), relation('supplier', 'Supplier', 'suppliers'), select('status', 'Status', ['Draft', 'Awaiting approval', 'Ordered', 'Part received', 'Received', 'Cancelled']), currency('amount', 'Total'), date('expectedDate', 'Expected date')], 'kanban', 'status')], pages: [{ id: 'purchasing', label: 'Purchasing', entityId: 'purchase-orders', view: 'kanban' }], metrics: [{ id: 'open-purchase-orders', label: 'Open purchase orders', entityId: 'purchase-orders', operation: 'count', statusNotEquals: 'Received' }] }),
  capability({ id: 'inventory.stock', label: 'Inventory and stock', module: 'inventory', description: 'On-hand, allocated and available quantities with reorder points.', signals: ['inventory', 'stock', 'materials', 'parts', 'physical goods'], dependencies: ['commerce.products'], entities: [entity('stock-items', 'Stock item', 'Inventory', 'name', [text('name', 'Item', true), relation('product', 'Product', 'products'), number('quantity', 'On hand'), number('allocated', 'Allocated'), number('reorderPoint', 'Reorder point'), select('status', 'Status', ['Available', 'Low stock', 'Out of stock'])])], pages: [{ id: 'inventory', label: 'Inventory', entityId: 'stock-items' }], metrics: [{ id: 'low-stock-items', label: 'Low-stock items', entityId: 'stock-items', operation: 'count' }] }),
  capability({ id: 'inventory.warehouses', label: 'Warehouses and locations', module: 'inventory', description: 'Storage locations, bins and internal movements.', signals: ['warehouse', 'storage location', 'multiple locations', 'bin'], dependencies: ['inventory.stock'], entities: [entity('warehouses', 'Warehouse', 'Warehouses', 'name', [text('name', 'Warehouse', true), text('address', 'Address'), select('status', 'Status', ['Active', 'Inactive'])]), entity('stock-movements', 'Stock movement', 'Stock movements', 'reference', [text('reference', 'Reference', true), relation('product', 'Product', 'products'), relation('warehouse', 'Warehouse', 'warehouses'), select('type', 'Movement', ['Receipt', 'Transfer', 'Issue', 'Adjustment']), number('quantity', 'Quantity'), date('date', 'Date')])], pages: [{ id: 'warehouses', label: 'Warehouses', entityId: 'warehouses' }, { id: 'stock-movements', label: 'Stock movements', entityId: 'stock-movements' }] }),
  capability({ id: 'inventory.traceability', label: 'Lot and serial traceability', module: 'inventory', description: 'Lots, serial numbers, expirations and product genealogy.', signals: ['lot', 'batch', 'serial', 'expiry', 'traceability'], dependencies: ['inventory.stock'], entities: [entity('lots', 'Lot', 'Lots and serials', 'number', [text('number', 'Lot or serial', true), relation('product', 'Product', 'products'), number('quantity', 'Quantity'), date('manufacturedDate', 'Manufactured'), date('expiryDate', 'Expires'), select('status', 'Status', ['Available', 'Quarantined', 'Consumed', 'Expired'])])], pages: [{ id: 'lots', label: 'Lots and serials', entityId: 'lots' }] }),
  capability({ id: 'logistics.shipping', label: 'Shipping and delivery', module: 'logistics', description: 'Physical shipments, carriers, tracking and delivery status.', signals: ['shipping', 'physical delivery', 'carrier', 'tracking number', 'order fulfilment'], dependencies: ['sales.orders'], entities: [entity('shipments', 'Shipment', 'Shipments', 'number', [text('number', 'Shipment', true), relation('order', 'Order', 'orders'), select('status', 'Status', ['Preparing', 'Ready', 'In transit', 'Delivered', 'Exception']), text('carrier', 'Carrier'), text('trackingNumber', 'Tracking number'), date('deliveryDate', 'Delivery date')], 'kanban', 'status')], pages: [{ id: 'shipping', label: 'Shipping', entityId: 'shipments', view: 'kanban' }] }),
  capability({ id: 'logistics.fleet', label: 'Fleet management', module: 'logistics', description: 'Vehicles, assignments, mileage and operating status.', signals: ['fleet', 'vehicle', 'truck', 'driver', 'mileage'], dependencies: ['people.directory'], entities: [entity('vehicles', 'Vehicle', 'Fleet', 'name', [text('name', 'Vehicle', true), text('registration', 'Registration'), select('status', 'Status', ['Available', 'Assigned', 'Maintenance', 'Retired']), relation('driver', 'Driver', 'employees'), number('mileage', 'Mileage')])], pages: [{ id: 'fleet', label: 'Fleet', entityId: 'vehicles' }] }),

  capability({ id: 'manufacturing.bom', label: 'Bills of materials', module: 'manufacturing', description: 'Product recipes, components and quantities.', signals: ['bill of materials', 'bom', 'recipe', 'components', 'assembly'], dependencies: ['commerce.products', 'inventory.stock'], entities: [entity('bills-of-material', 'Bill of materials', 'Bills of materials', 'name', [text('name', 'BOM', true), relation('product', 'Finished product', 'products'), text('version', 'Version'), select('status', 'Status', ['Draft', 'Active', 'Obsolete']), long('components', 'Components and quantities')])], pages: [{ id: 'bills-of-material', label: 'Bills of materials', entityId: 'bills-of-material' }] }),
  capability({ id: 'manufacturing.production', label: 'Production planning and work orders', module: 'manufacturing', description: 'Demand, work centers, production orders and completion.', signals: ['manufacturing', 'production', 'factory', 'work order', 'work center'], dependencies: ['manufacturing.bom', 'people.directory'], entities: [entity('production-orders', 'Production order', 'Production', 'number', [text('number', 'Production order', true), relation('product', 'Product', 'products'), select('status', 'Status', ['Planned', 'Materials ready', 'In production', 'Quality check', 'Complete', 'Cancelled']), number('quantity', 'Quantity'), date('startDate', 'Start date'), date('dueDate', 'Due date'), text('workCenter', 'Work center')], 'kanban', 'status')], pages: [{ id: 'production', label: 'Production', entityId: 'production-orders', view: 'kanban' }], metrics: [{ id: 'production-orders-open', label: 'Open production orders', entityId: 'production-orders', operation: 'count', statusNotEquals: 'Complete' }] }),
  capability({ id: 'quality.inspections', label: 'Quality control', module: 'quality', description: 'Inspection plans, checks, defects and corrective actions.', signals: ['quality control', 'inspection', 'defect', 'nonconformance', 'quality assurance'], dependencies: [], entities: [entity('quality-checks', 'Quality check', 'Quality', 'name', [text('name', 'Inspection', true), select('status', 'Result', ['Planned', 'Pass', 'Fail', 'Hold']), date('date', 'Date'), long('findings', 'Findings'), long('correctiveAction', 'Corrective action')], 'kanban', 'status')], pages: [{ id: 'quality', label: 'Quality', entityId: 'quality-checks', view: 'kanban' }] }),
  capability({ id: 'maintenance.assets', label: 'Asset maintenance', module: 'maintenance', description: 'Internal equipment, preventive plans, failures and service cost.', signals: ['maintenance', 'equipment', 'machinery', 'preventive maintenance', 'downtime'], dependencies: [], entities: [entity('equipment', 'Equipment', 'Equipment', 'name', [text('name', 'Equipment', true), text('serialNumber', 'Serial number'), select('status', 'Status', ['Available', 'In use', 'Maintenance', 'Out of service']), date('nextMaintenance', 'Next maintenance'), currency('lifetimeCost', 'Lifetime cost')]), entity('maintenance-orders', 'Maintenance order', 'Maintenance', 'description', [text('description', 'Maintenance work', true), relation('equipment', 'Equipment', 'equipment'), select('status', 'Status', ['Requested', 'Scheduled', 'In progress', 'Complete']), date('dueDate', 'Due date'), currency('cost', 'Cost')], 'kanban', 'status')], pages: [{ id: 'equipment', label: 'Equipment', entityId: 'equipment' }, { id: 'maintenance', label: 'Maintenance', entityId: 'maintenance-orders', view: 'kanban' }], workflows: [{ id: 'maintenance-due', name: 'Maintenance due', entityId: 'maintenance-orders', event: 'updated', field: 'status', equals: 'Requested', message: 'Equipment maintenance requires scheduling.' }] }),

  capability({ id: 'finance.invoicing', label: 'Invoicing and receivables', module: 'finance', description: 'One-time invoices, due dates, reminders and payment status.', signals: ['invoice', 'billing', 'accounts receivable', 'charge customer'], dependencies: ['crm.contacts'], entities: [entity('invoices', 'Invoice', 'Invoices', 'number', [text('number', 'Invoice number', true), relation('customer', 'Client', 'customers'), select('status', 'Status', ['Draft', 'Sent', 'Part paid', 'Paid', 'Overdue', 'Void']), currency('amount', 'Total'), currency('balance', 'Balance'), date('dueDate', 'Due date')])], pages: [{ id: 'invoices', label: 'Invoices', entityId: 'invoices' }], metrics: [{ id: 'outstanding-invoices', label: 'Outstanding invoices', entityId: 'invoices', operation: 'sum', field: 'balance', format: 'currency', statusNotEquals: 'Paid' }], workflows: [{ id: 'invoice-overdue', name: 'Overdue invoice alert', entityId: 'invoices', event: 'updated', field: 'status', equals: 'Overdue', message: 'An invoice is overdue.' }] }),
  capability({ id: 'finance.payments', label: 'Payment collection', module: 'finance', description: 'Incoming payments, methods, allocation and refunds.', signals: ['collect payment', 'payment gateway', 'credit card', 'bank transfer', 'cash payment', 'refund'], dependencies: ['finance.invoicing'], entities: [entity('payments', 'Payment', 'Payments', 'reference', [text('reference', 'Payment reference', true), relation('invoice', 'Invoice', 'invoices'), currency('amount', 'Amount'), select('method', 'Method', ['Card', 'Bank transfer', 'Cash', 'Direct debit', 'Other']), select('status', 'Status', ['Pending', 'Completed', 'Failed', 'Refunded']), date('date', 'Date')])], pages: [{ id: 'payments', label: 'Payments', entityId: 'payments' }], metrics: [{ id: 'payments-received', label: 'Payments received', entityId: 'payments', operation: 'sum', field: 'amount', format: 'currency' }] }),
  capability({ id: 'finance.expenses', label: 'Expense and receipt tracking', module: 'finance', description: 'Operational spending, categories, receipts and approval.', signals: ['expense', 'receipt', 'business cost', 'spending'], dependencies: [], entities: [entity('expenses', 'Expense', 'Expenses', 'description', [text('description', 'Expense', true), currency('amount', 'Amount'), text('category', 'Category'), select('status', 'Status', ['Draft', 'Submitted', 'Approved', 'Paid', 'Rejected']), date('date', 'Date'), { id: 'receipt', label: 'Receipt', type: 'file' }])], pages: [{ id: 'expenses', label: 'Expenses', entityId: 'expenses' }], metrics: [{ id: 'expenses-total', label: 'Expenses', entityId: 'expenses', operation: 'sum', field: 'amount', format: 'currency' }] }),
  capability({ id: 'accounting.ledger', label: 'Accounting and general ledger', module: 'accounting', description: 'Chart of accounts, journals, periods and financial statements.', signals: ['accounting', 'bookkeeping', 'general ledger', 'journal entry', 'balance sheet'], dependencies: ['finance.invoicing', 'finance.expenses'], entities: [entity('accounts', 'Account', 'Chart of accounts', 'name', [text('name', 'Account', true), text('code', 'Code'), select('type', 'Type', ['Asset', 'Liability', 'Equity', 'Revenue', 'Expense']), select('status', 'Status', ['Active', 'Archived'])]), entity('journal-entries', 'Journal entry', 'Journal entries', 'reference', [text('reference', 'Reference', true), date('date', 'Date'), text('account', 'Account'), currency('debit', 'Debit'), currency('credit', 'Credit'), long('memo', 'Memo')])], pages: [{ id: 'chart-of-accounts', label: 'Chart of accounts', entityId: 'accounts' }, { id: 'journal-entries', label: 'Journal entries', entityId: 'journal-entries' }] }),
  capability({ id: 'finance.budgets', label: 'Budgets and financial goals', module: 'finance', description: 'Monthly or yearly targets versus actuals.', signals: ['budget', 'financial goal', 'forecast', 'target'], dependencies: [], entities: [entity('budgets', 'Budget', 'Budgets', 'name', [text('name', 'Budget', true), text('category', 'Category'), currency('target', 'Target'), currency('actual', 'Actual'), date('startDate', 'Start date'), date('endDate', 'End date')])], pages: [{ id: 'budgets', label: 'Budgets', entityId: 'budgets' }] }),
  capability({ id: 'finance.tax', label: 'Sales tax administration', module: 'accounting', description: 'Tax rates, taxable sales and filing periods.', signals: ['sales tax', 'vat', 'gst', 'tax on sales'], dependencies: ['finance.invoicing'], entities: [entity('tax-periods', 'Tax period', 'Tax', 'name', [text('name', 'Period', true), date('startDate', 'Start date'), date('endDate', 'End date'), currency('taxCollected', 'Tax collected'), select('status', 'Status', ['Open', 'Ready to file', 'Filed'])])], pages: [{ id: 'tax', label: 'Tax', entityId: 'tax-periods' }] }),

  capability({ id: 'documents.repository', label: 'Document repository', module: 'documents', description: 'Files connected to clients, projects, people and transactions.', signals: ['document', 'file storage', 'repository', 'project files', 'folder'], dependencies: [], entities: [entity('documents', 'Document', 'Documents', 'name', [text('name', 'Document', true), { id: 'file', label: 'File', type: 'file', required: true }, text('linkedTo', 'Linked to'), text('version', 'Version'), select('status', 'Status', ['Draft', 'Current', 'Archived']), date('expiryDate', 'Expiry date')])], pages: [{ id: 'documents', label: 'Documents', entityId: 'documents' }] }),
  capability({ id: 'documents.approvals', label: 'Approvals', module: 'documents', description: 'Requests, decision makers, status and audit trail.', signals: ['approval', 'manager approval', 'pending approval', 'sign off'], dependencies: ['people.directory'], entities: [entity('approvals', 'Approval', 'Approvals', 'subject', [text('subject', 'Approval', true), select('type', 'Type', ['Expense', 'Document', 'Purchase', 'Project', 'Other']), select('status', 'Status', ['Requested', 'Approved', 'Rejected', 'Cancelled']), relation('requestedBy', 'Requested by', 'employees'), relation('approver', 'Approver', 'employees'), date('dueDate', 'Due date')])], pages: [{ id: 'approvals', label: 'Approvals', entityId: 'approvals' }], metrics: [{ id: 'pending-approvals', label: 'Pending approvals', entityId: 'approvals', operation: 'count', statusNotEquals: 'Approved' }] }),
  capability({ id: 'documents.esign', label: 'Electronic signatures', module: 'documents', description: 'Documents sent for signature and completion tracking.', signals: ['electronic signature', 'e-sign', 'signature request', 'sign contract'], dependencies: ['documents.repository'], entities: [entity('signature-requests', 'Signature request', 'Signatures', 'subject', [text('subject', 'Document', true), relation('document', 'Document', 'documents'), select('status', 'Status', ['Draft', 'Sent', 'Viewed', 'Signed', 'Declined', 'Expired']), text('signer', 'Signer'), date('dueDate', 'Due date')])], pages: [{ id: 'signatures', label: 'Signatures', entityId: 'signature-requests' }] }),
  capability({ id: 'documents.templates', label: 'Document generation', module: 'documents', description: 'Reusable templates populated with workspace data.', signals: ['document template', 'generate contract', 'generate proposal', 'sop template'], dependencies: ['documents.repository'], entities: [entity('document-templates', 'Template', 'Document templates', 'name', [text('name', 'Template', true), select('type', 'Type', ['Contract', 'Proposal', 'SOP', 'Invoice', 'Other']), select('status', 'Status', ['Draft', 'Active', 'Archived']), { id: 'template', label: 'Template file', type: 'file' }])], pages: [{ id: 'document-templates', label: 'Templates', entityId: 'document-templates' }] }),

  capability({ id: 'support.tickets', label: 'Customer support', module: 'support', description: 'Questions, change requests, incidents and service levels.', signals: ['support request', 'ticket', 'customer question', 'help desk', 'inquiry'], dependencies: ['crm.contacts', 'people.directory'], entities: [entity('tickets', 'Ticket', 'Support', 'subject', [text('subject', 'Subject', true), relation('customer', 'Client', 'customers'), select('status', 'Status', ['New', 'Triage', 'In progress', 'Waiting', 'Resolved', 'Closed']), select('priority', 'Priority', ['Low', 'Normal', 'High', 'Urgent']), relation('assignee', 'Assigned to', 'employees'), date('dueDate', 'SLA due'), long('description', 'Description')], 'kanban', 'status')], pages: [{ id: 'support', label: 'Support', entityId: 'tickets', view: 'kanban' }], metrics: [{ id: 'open-support', label: 'Open support requests', entityId: 'tickets', operation: 'count', statusNotEquals: 'Closed' }] }),
  capability({ id: 'support.knowledge', label: 'Knowledge base', module: 'support', description: 'Internal or customer-facing guidance and procedures.', signals: ['knowledge base', 'help center', 'faq', 'support article'], dependencies: [], entities: [entity('knowledge-articles', 'Article', 'Knowledge base', 'title', [text('title', 'Title', true), text('category', 'Category'), select('status', 'Status', ['Draft', 'Published', 'Archived']), long('content', 'Content')])], pages: [{ id: 'knowledge', label: 'Knowledge base', entityId: 'knowledge-articles' }] }),

  capability({ id: 'people.directory', label: 'Team directory', module: 'team', description: 'Employees, contractors, roles and availability.', signals: ['employee', 'team', 'staff', 'worker', 'contractor', 'crew'], dependencies: [], entities: [entity('employees', 'Team member', 'Team', 'name', [text('name', 'Name', true), text('jobTitle', 'Job title'), { id: 'email', label: 'Email', type: 'email' }, select('employmentType', 'Type', ['Employee', 'Contractor', 'Freelancer']), select('status', 'Status', ['Active', 'On leave', 'Inactive']), date('startDate', 'Start date')])], pages: [{ id: 'team', label: 'Team', entityId: 'employees' }] }),
  capability({ id: 'people.time-off', label: 'Leave and time off', module: 'hr', description: 'Vacation balances, requests and approvals.', signals: ['time off', 'vacation', 'leave request', 'pto'], dependencies: ['people.directory', 'documents.approvals'], entities: [entity('leave-requests', 'Leave request', 'Time off', 'name', [text('name', 'Request', true), relation('employee', 'Team member', 'employees'), select('type', 'Type', ['Vacation', 'Sick', 'Personal', 'Other']), date('startDate', 'Start date'), date('endDate', 'End date'), select('status', 'Status', ['Requested', 'Approved', 'Rejected', 'Cancelled'])])], pages: [{ id: 'time-off', label: 'Time off', entityId: 'leave-requests' }] }),
  capability({ id: 'people.attendance', label: 'Attendance and shifts', module: 'hr', description: 'Clock-in, shifts, attendance and hours.', signals: ['attendance', 'clock in', 'shift', 'rota', 'schedule employees'], dependencies: ['people.directory'], entities: [entity('shifts', 'Shift', 'Shifts', 'name', [text('name', 'Shift', true), relation('employee', 'Team member', 'employees'), date('date', 'Date'), text('startTime', 'Start time'), text('endTime', 'End time'), select('status', 'Status', ['Scheduled', 'Worked', 'Absent', 'Cancelled'])], 'calendar', undefined, 'date')], pages: [{ id: 'shifts', label: 'Shifts', entityId: 'shifts', view: 'calendar' }] }),
  capability({ id: 'people.recruiting', label: 'Recruiting', module: 'hr', description: 'Open positions, candidates, interviews and offers.', signals: ['recruiting', 'hiring', 'candidate', 'job opening'], dependencies: [], entities: [entity('candidates', 'Candidate', 'Recruiting', 'name', [text('name', 'Candidate', true), text('position', 'Position'), select('status', 'Stage', ['Applied', 'Screening', 'Interview', 'Offer', 'Hired', 'Rejected']), { id: 'email', label: 'Email', type: 'email' }, date('nextDate', 'Next step date')], 'kanban', 'status')], pages: [{ id: 'recruiting', label: 'Recruiting', entityId: 'candidates', view: 'kanban' }] }),
  capability({ id: 'people.payroll', label: 'Payroll preparation', module: 'payroll', description: 'Pay periods, compensation inputs and payroll status.', signals: ['payroll', 'salary', 'pay employees', 'wages'], dependencies: ['people.directory'], entities: [entity('pay-runs', 'Pay run', 'Payroll', 'name', [text('name', 'Pay period', true), date('startDate', 'Start date'), date('endDate', 'End date'), currency('grossPay', 'Gross pay'), currency('netPay', 'Net pay'), select('status', 'Status', ['Draft', 'Review', 'Approved', 'Paid'])])], pages: [{ id: 'payroll', label: 'Payroll', entityId: 'pay-runs' }] }),

  capability({ id: 'compliance.controls', label: 'Compliance controls', module: 'compliance', description: 'Policies, evidence, controls, owners and review dates.', signals: ['compliance', 'gdpr', 'soc 2', 'iso', 'regulation', 'audit requirement'], dependencies: ['documents.repository', 'documents.approvals', 'people.directory'], entities: [entity('controls', 'Control', 'Compliance', 'name', [text('name', 'Control', true), text('framework', 'Framework'), select('status', 'Status', ['Not started', 'In progress', 'Implemented', 'Needs review']), relation('owner', 'Owner', 'employees'), date('reviewDate', 'Review date'), { id: 'evidence', label: 'Evidence', type: 'file' }])], pages: [{ id: 'compliance', label: 'Compliance', entityId: 'controls' }] }),
  capability({ id: 'analytics.reporting', label: 'Operational reporting', module: 'analytics', description: 'Saved reports and review cadence across the business.', signals: ['operational report', 'kpi reporting', 'performance review', 'analytics'], dependencies: [], entities: [entity('reports', 'Report', 'Reports', 'name', [text('name', 'Report', true), text('metric', 'Metric'), select('cadence', 'Review cadence', ['Daily', 'Weekly', 'Monthly', 'Quarterly']), select('status', 'Status', ['Active', 'Paused'])])], pages: [{ id: 'reports', label: 'Reports', entityId: 'reports' }] }),

  capability({ id: 'vertical.construction-controls', label: 'Construction controls', module: 'projects', description: 'Bids, RFIs, submittals, change orders and project commitments.', signals: ['construction', 'rfi', 'submittal', 'change order', 'general contractor'], dependencies: ['work.projects', 'documents.repository', 'documents.approvals'], entities: [entity('change-orders', 'Change order', 'Change orders', 'number', [text('number', 'Change order', true), relation('project', 'Project', 'projects'), select('status', 'Status', ['Draft', 'Submitted', 'Approved', 'Rejected']), currency('amount', 'Amount'), long('scope', 'Scope')]), entity('rfis', 'RFI', 'RFIs', 'subject', [text('subject', 'RFI', true), relation('project', 'Project', 'projects'), select('status', 'Status', ['Open', 'Answered', 'Closed']), date('dueDate', 'Due date')])], pages: [{ id: 'change-orders', label: 'Change orders', entityId: 'change-orders' }, { id: 'rfis', label: 'RFIs', entityId: 'rfis' }] }),
  capability({ id: 'vertical.healthcare', label: 'Patient and care administration', module: 'processes', description: 'Patients, encounters, authorizations and claims administration.', signals: ['clinic', 'patient', 'medical practice', 'dental', 'therapy'], dependencies: ['work.scheduling', 'documents.repository', 'compliance.controls'], entities: [entity('patients', 'Patient', 'Patients', 'name', [text('name', 'Patient', true), { id: 'email', label: 'Email', type: 'email' }, { id: 'phone', label: 'Phone', type: 'phone' }, date('dateOfBirth', 'Date of birth'), select('status', 'Status', ['Active', 'Inactive'])]), entity('claims', 'Claim', 'Claims', 'number', [text('number', 'Claim', true), relation('patient', 'Patient', 'patients'), select('status', 'Status', ['Draft', 'Submitted', 'Accepted', 'Denied', 'Paid']), currency('amount', 'Amount'), date('date', 'Date')])], pages: [{ id: 'patients', label: 'Patients', entityId: 'patients' }, { id: 'claims', label: 'Claims', entityId: 'claims' }] }),
  capability({ id: 'vertical.property', label: 'Property and tenancy management', module: 'processes', description: 'Properties, units, leases, tenants and maintenance.', signals: ['property management', 'real estate', 'tenant', 'lease', 'rental property'], dependencies: ['crm.contacts', 'sales.contracts', 'finance.invoicing', 'maintenance.assets'], entities: [entity('properties', 'Property', 'Properties', 'name', [text('name', 'Property', true), text('address', 'Address'), number('units', 'Units'), select('status', 'Status', ['Occupied', 'Part occupied', 'Vacant', 'Maintenance'])]), entity('leases', 'Lease', 'Leases', 'name', [text('name', 'Lease', true), relation('customer', 'Tenant', 'customers'), relation('property', 'Property', 'properties'), date('startDate', 'Start date'), date('endDate', 'End date'), currency('rent', 'Rent'), select('status', 'Status', ['Draft', 'Active', 'Ending', 'Ended'])])], pages: [{ id: 'properties', label: 'Properties', entityId: 'properties' }, { id: 'leases', label: 'Leases', entityId: 'leases' }] }),
  capability({ id: 'vertical.hospitality', label: 'Hospitality operations', module: 'processes', description: 'Reservations, tables or rooms, service and daily operations.', signals: ['restaurant', 'hotel', 'hospitality', 'table reservation', 'room booking'], dependencies: ['commerce.pos', 'work.scheduling', 'inventory.stock', 'procurement.purchasing'], entities: [entity('reservations', 'Reservation', 'Reservations', 'name', [text('name', 'Guest', true), date('date', 'Date'), text('time', 'Time'), number('partySize', 'Party size'), select('status', 'Status', ['Booked', 'Confirmed', 'Seated', 'Complete', 'Cancelled'])], 'calendar', undefined, 'date')], pages: [{ id: 'reservations', label: 'Reservations', entityId: 'reservations', view: 'calendar' }] }),
  capability({ id: 'vertical.education', label: 'Education program administration', module: 'processes', description: 'Learners, courses, cohorts, enrollment and attendance.', signals: ['school', 'training company', 'course', 'student', 'education'], dependencies: ['crm.contacts', 'work.scheduling', 'documents.repository'], entities: [entity('courses', 'Course', 'Courses', 'name', [text('name', 'Course', true), select('status', 'Status', ['Draft', 'Open', 'Running', 'Complete']), date('startDate', 'Start date'), date('endDate', 'End date')]), entity('enrollments', 'Enrollment', 'Enrollments', 'name', [text('name', 'Enrollment', true), relation('course', 'Course', 'courses'), relation('student', 'Student', 'customers'), select('status', 'Status', ['Applied', 'Enrolled', 'Complete', 'Withdrawn'])])], pages: [{ id: 'courses', label: 'Courses', entityId: 'courses' }, { id: 'enrollments', label: 'Enrollments', entityId: 'enrollments' }] }),
  capability({ id: 'vertical.nonprofit', label: 'Nonprofit funding and programs', module: 'processes', description: 'Donors, grants, programs and restricted funding.', signals: ['nonprofit', 'charity', 'donor', 'grant', 'fundraising'], dependencies: ['crm.contacts', 'work.projects', 'finance.expenses'], entities: [entity('grants', 'Grant', 'Grants', 'name', [text('name', 'Grant', true), text('funder', 'Funder'), currency('amount', 'Amount'), select('status', 'Status', ['Prospect', 'Applied', 'Awarded', 'Reporting', 'Closed']), date('dueDate', 'Due date')]), entity('donations', 'Donation', 'Donations', 'reference', [text('reference', 'Donation', true), relation('customer', 'Donor', 'customers'), currency('amount', 'Amount'), date('date', 'Date')])], pages: [{ id: 'grants', label: 'Grants', entityId: 'grants' }, { id: 'donations', label: 'Donations', entityId: 'donations' }] }),
]

/** The whole buildable surface: the core systems plus the extended ERP and CRM coverage. */
export const capabilityCatalog: CapabilityDefinition[] = [...coreCapabilities, ...commerceCapabilities, ...operationsCapabilities, ...financeCapabilities]

export const capabilityIds = capabilityCatalog.map(item => item.id)
export const capabilityById = new Map(capabilityCatalog.map(item => [item.id, item]))

export interface IndustryCapabilityPack {
  id: string
  label: string
  signals: string[]
  capabilities: string[]
}

const corePacks: IndustryCapabilityPack[] = [
  { id: 'agency', label: 'Agency', signals: ['marketing agency', 'creative agency', 'advertising agency', 'design agency', 'seo agency'], capabilities: ['crm.contacts', 'crm.pipeline', 'work.projects', 'work.tasks', 'finance.invoicing', 'finance.expenses', 'documents.repository'] },
  { id: 'professional-services', label: 'Professional services', signals: ['consulting', 'consultancy', 'consultant', 'accounting firm', 'law firm', 'advisory', 'professional services'], capabilities: ['crm.contacts', 'crm.pipeline', 'crm.activities', 'sales.quotes', 'sales.contracts', 'work.projects', 'work.tasks', 'work.time', 'work.resources', 'finance.invoicing', 'finance.expenses', 'documents.repository', 'documents.templates', 'people.directory'] },
  { id: 'saas', label: 'SaaS', signals: ['saas', 'subscription software', 'software platform', 'b2b software'], capabilities: ['crm.contacts', 'crm.pipeline', 'crm.activities', 'sales.quotes', 'sales.contracts', 'subscriptions.billing', 'subscriptions.success', 'support.tickets', 'support.knowledge', 'finance.invoicing', 'finance.payments', 'marketing.attribution', 'people.directory', 'analytics.reporting'] },
  { id: 'manufacturing', label: 'Manufacturing', signals: ['manufacturing', 'manufacturer', 'factory', 'fabrication', 'assembly', 'production line'], capabilities: ['crm.contacts', 'sales.quotes', 'sales.orders', 'commerce.products', 'procurement.suppliers', 'procurement.purchasing', 'inventory.stock', 'inventory.warehouses', 'inventory.traceability', 'manufacturing.bom', 'manufacturing.production', 'quality.inspections', 'maintenance.assets', 'logistics.shipping', 'finance.invoicing', 'finance.expenses', 'people.directory'] },
  { id: 'retail', label: 'Retail and e-commerce', signals: ['retail', 'ecommerce', 'e-commerce', 'online store', 'shopify', 'shop'], capabilities: ['crm.contacts', 'commerce.products', 'commerce.ecommerce', 'sales.orders', 'inventory.stock', 'inventory.warehouses', 'logistics.shipping', 'commerce.returns', 'finance.payments', 'finance.expenses', 'support.tickets'] },
  { id: 'field-service', label: 'Field service', signals: ['field service', 'hvac', 'plumbing', 'electrician', 'landscaping', 'repair service', 'installation service'], capabilities: ['crm.contacts', 'sales.quotes', 'sales.contracts', 'work.scheduling', 'service.field-work', 'service.assets', 'inventory.stock', 'procurement.purchasing', 'finance.invoicing', 'finance.payments', 'people.directory'] },
  { id: 'construction', label: 'Construction', signals: ['construction', 'general contractor', 'building contractor', 'civil engineering', 'home builder'], capabilities: ['crm.contacts', 'crm.pipeline', 'sales.quotes', 'sales.contracts', 'work.projects', 'work.tasks', 'work.resources', 'procurement.suppliers', 'procurement.purchasing', 'inventory.stock', 'finance.invoicing', 'finance.expenses', 'documents.repository', 'documents.approvals', 'vertical.construction-controls', 'people.directory'] },
  { id: 'healthcare', label: 'Healthcare', signals: ['clinic', 'medical practice', 'dental', 'therapy practice', 'healthcare'], capabilities: ['vertical.healthcare', 'work.scheduling', 'finance.invoicing', 'finance.payments', 'documents.repository', 'documents.approvals', 'people.directory', 'compliance.controls'] },
  { id: 'property', label: 'Property management', signals: ['property management', 'real estate', 'rental property', 'landlord'], capabilities: ['vertical.property', 'crm.contacts', 'sales.contracts', 'finance.invoicing', 'finance.payments', 'documents.repository', 'maintenance.assets'] },
  { id: 'hospitality', label: 'Hospitality', signals: ['restaurant', 'hotel', 'hospitality', 'cafe', 'bar'], capabilities: ['vertical.hospitality', 'commerce.products', 'commerce.pos', 'inventory.stock', 'procurement.purchasing', 'work.scheduling', 'people.directory', 'people.attendance', 'finance.expenses'] },
  { id: 'logistics', label: 'Logistics', signals: ['logistics', 'trucking', 'freight', 'delivery company', 'transport company'], capabilities: ['crm.contacts', 'sales.quotes', 'sales.orders', 'logistics.shipping', 'logistics.fleet', 'work.scheduling', 'maintenance.assets', 'finance.invoicing', 'finance.expenses', 'people.directory'] },
  { id: 'education', label: 'Education', signals: ['school', 'training company', 'course provider', 'education'], capabilities: ['vertical.education', 'crm.contacts', 'work.scheduling', 'finance.invoicing', 'finance.payments', 'documents.repository', 'people.directory'] },
  { id: 'nonprofit', label: 'Nonprofit', signals: ['nonprofit', 'charity', 'foundation', 'ngo'], capabilities: ['vertical.nonprofit', 'crm.contacts', 'work.projects', 'finance.expenses', 'finance.budgets', 'documents.repository', 'people.directory'] },
  { id: 'wholesale', label: 'Wholesale and distribution', signals: ['wholesale', 'distributor', 'distribution company'], capabilities: ['crm.contacts', 'crm.pipeline', 'sales.quotes', 'sales.orders', 'commerce.products', 'procurement.suppliers', 'procurement.purchasing', 'inventory.stock', 'inventory.warehouses', 'inventory.traceability', 'logistics.shipping', 'finance.invoicing', 'finance.payments', 'finance.expenses'] },
  { id: 'rental', label: 'Rental operations', signals: ['equipment rental', 'vehicle rental', 'rental company', 'hire business'], capabilities: ['crm.contacts', 'sales.quotes', 'sales.contracts', 'work.scheduling', 'service.assets', 'maintenance.assets', 'finance.invoicing', 'finance.payments', 'documents.esign'] },
]

/** Core packs plus the extended sector coverage, so every NAICS sector resolves to a real base. */
export const industryCapabilityPacks: IndustryCapabilityPack[] = [...corePacks, ...extendedIndustryPacks]

/**
 * The company's own words — and only those.
 *
 * The architecture used to be folded in here too, but BO writes the architecture from the
 * capabilities it already chose, so its labels and descriptions came straight back in as "evidence".
 * The word "approval" inside BO's own description of expense tracking was enough to attach the
 * approvals system to a business that never mentioned approvals, and each round added more. The
 * architecture still has a say through `capabilityIds` and `excludedCapabilityIds`, which is an
 * explicit choice rather than a text match.
 */
function normalizedText(state: BusinessState, _architecture: ArchitectureContext) {
  return [state.companySummary, state.industry, ...state.businessModel, ...state.productsOrServices, ...state.customers, ...state.revenueModel, ...state.team, ...state.operations, ...state.resources, ...state.goals, ...state.knownEntities, ...state.knownWorkflows, ...state.softwareImplications, ...state.facts.map(item => `${item.topic} ${item.value}`)].join(' ').toLowerCase()
}

export function selectIndustryCapabilityPack(text: string) {
  const normalized = text.toLowerCase()
  return industryCapabilityPacks.map(pack => ({ pack, score: pack.signals.reduce((score, signal) => score + (saysSignal(normalized, signal) ? signal.split(' ').length + 1 : 0), 0) })).sort((left, right) => right.score - left.score)[0]
}

function explicitlyExcluded(text: string) {
  const excluded = new Set<string>()
  if (/no (physical|stock|inventory)|do not (sell|store|buy) physical|digital products? only|services? only/.test(text)) ['inventory.stock', 'inventory.warehouses', 'inventory.traceability', 'logistics.shipping', 'manufacturing.bom', 'manufacturing.production', 'quality.inspections', 'procurement.purchasing'].forEach(id => excluded.add(id))
  // "Solo consultant" and "sole trader" are how people describe themselves far more often than "solo
  // founder". The team directory stays whatever they say: twenty-eight capabilities depend on it, so
  // removing it would take tasks, timesheets and the schedule with it. What goes is the staffing
  // administration around it — capacity planning and leave for a company of one.
  if (/no employees|no team|just me|work alone|\bsolo\b|\bsole (trader|operator|practitioner)\b/.test(text)) ['people.time-off', 'people.attendance', 'people.recruiting', 'people.payroll', 'work.resources', 'work.shifts'].forEach(id => excluded.add(id))
  if (/no subscriptions?|one[- ]off only|no recurring/.test(text)) ['subscriptions.billing', 'subscriptions.success'].forEach(id => excluded.add(id))
  if (/no shipping|pickup only|digital delivery/.test(text)) excluded.add('logistics.shipping')
  return excluded
}

export interface CapabilityPlan {
  pack: IndustryCapabilityPack | null
  selected: CapabilityDefinition[]
  excluded: string[]
  reasons: Record<string, string>
  research: BusinessResearch
}

export function planCapabilities(state: BusinessState, architecture: ArchitectureContext): CapabilityPlan {
  const text = normalizedText(state, architecture)
  const research = researchBusiness({ text })
  const selected = new Set<string>()
  const reasons: Record<string, string> = {}
  const explicitExcluded = new Set([...(architecture.excludedCapabilityIds ?? []), ...explicitlyExcluded(text), ...research.exclude.map(item => item.capabilityId)])
  const packMatch = selectIndustryCapabilityPack(`${state.industry} ${state.companySummary}`)
  // When no signal matches, fall back to the industry taxonomy so an unusual business still gets a
  // real operating base rather than the conservative general one.
  const taxonomyPack = packMatch?.score ? null : industryCapabilityPacks.find(item => item.id === research.archetype?.id)
  const pack = packMatch?.score ? packMatch.pack : taxonomyPack ?? null
  for (const id of architecture.capabilityIds ?? []) if (capabilityById.has(id)) { selected.add(id); reasons[id] = 'Selected by BO architecture' }
  for (const decision of research.include) if (capabilityById.has(decision.capabilityId) && !explicitExcluded.has(decision.capabilityId)) { selected.add(decision.capabilityId); reasons[decision.capabilityId] ||= decision.reason }
  if (pack) for (const id of pack.capabilities) if (!explicitExcluded.has(id)) { selected.add(id); reasons[id] ||= `${pack.label} operating base` }
  for (const definition of capabilityCatalog) {
    if (explicitExcluded.has(definition.id) || selected.has(definition.id)) continue
    const signal = definition.signals.find(candidate => saysSignal(text, candidate))
    if (signal) { selected.add(definition.id); reasons[definition.id] = `Business evidence: ${signal}` }
  }
  if (!selected.size) ['crm.contacts', 'finance.invoicing', 'finance.expenses', 'documents.repository'].forEach(id => { selected.add(id); reasons[id] = 'Conservative general-business base' })
  let changed = true
  while (changed) {
    changed = false
    for (const id of [...selected]) for (const dependency of capabilityById.get(id)?.dependencies ?? []) {
      if (!explicitExcluded.has(dependency) && !selected.has(dependency)) { selected.add(dependency); reasons[dependency] = `Required by ${capabilityById.get(id)?.label}`; changed = true }
    }
  }
  for (const id of explicitExcluded) selected.delete(id)
  let pruned = true
  while (pruned) {
    pruned = false
    for (const id of [...selected]) if ((capabilityById.get(id)?.dependencies ?? []).some(dependency => explicitExcluded.has(dependency))) { selected.delete(id); pruned = true }
  }
  return { pack, selected: [...selected].map(id => capabilityById.get(id)).filter(Boolean) as CapabilityDefinition[], excluded: [...explicitExcluded], reasons, research }
}

export function capabilityCatalogPrompt() {
  const grouped = new Map<ModuleId, string[]>()
  for (const item of capabilityCatalog) grouped.set(item.module, [...(grouped.get(item.module) ?? []), `${item.id}=${item.label}`])
  return [...grouped.entries()].map(([module, items]) => `${module}: ${items.join(', ')}`).join('\n')
}
